//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

 
 

@interface PSDJsBridge : NSObject  
{
   
}


- (void)_doFlushMessageQueue:(id)arg1 url:(id)arg2;
//存储好友信息
-(void)saveFriendsInfo:(NSArray *)array;
//保存能量气泡
-(void)saveBubblesInfo:(NSArray *)array;
@end

